/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile
         * @description Параметры профиля для формы запуска: шаг, приёмы размещения, галочки этапов.
         */
        get: operations["profile_api_v1_profiles__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Последние прогоны, новые первыми.
         */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Принять чертёж или улицу из каталога и поставить прогон в очередь.
         *
         *     Источник ровно один: свой чертёж (`file`, к нему комплект `extra`) или улица пилотного
         *     проекта (`street`, её комплект уже лежит в каталоге). Статус: GET /runs/{id}.
         */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Demo Run
         * @description Прогон встроенного фрагмента улицы Берзарина с профилем по умолчанию.
         *
         *     Фрагмент лежит в пакете: на стенде жюри датасета нет, а показывать сервис надо с
         *     первого клика, не заставляя искать DXF. Статус: GET /runs/{id}.
         */
        post: operations["create_demo_run_api_v1_runs_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Статус прогона, сводка и ссылки на артефакты.
         */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Скачать артефакт: result.dxf, plan.json, interpretations.csv и другие.
         *
         *     Текстовые артефакты отдаются обычным ответом, а не FileResponse, намеренно. Granian
         *     умеет отправлять файл в обход ASGI-конвейера (расширение pathsend), и тогда сжатие
         *     middleware не применяется: подоснова Берзарина уехала бы в браузер на 12,9 МБ вместо
         *     1,3 МБ. Крупный result.dxf, наоборот, скачивают целиком и жать его незачем.
         */
        get: operations["get_artifact_api_v1_runs__run_id__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check
         * @description Проверить точку по нормам: тем же индексом ограничений, что и сам прогон.
         */
        post: operations["check_api_v1_runs__run_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Draft */
        get: operations["draft_api_v1_runs__run_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/edits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit
         * @description Применить правки к плану прогона. DXF при этом не переписывается.
         */
        post: operations["edit_api_v1_runs__run_id__edits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Photos
         * @description Фото прогона, новые сверху, и можно ли делать новые на этом сервере.
         */
        get: operations["list_photos_api_v1_runs__run_id__photos_get"];
        put?: never;
        /**
         * Create Photo
         * @description Поставить кадр в очередь модели. Статус: GET по адресу из Location.
         */
        post: operations["create_photo_api_v1_runs__run_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Photo */
        get: operations["get_photo_api_v1_runs__run_id__photos__photo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/photos/{photo_id}/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Photo File
         * @description Кадр 3D-вида (source), выход модели (raw) или увеличенное фото (photo).
         */
        get: operations["get_photo_file_api_v1_runs__run_id__photos__photo_id___kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild
         * @description Переписать result.dxf и все артефакты по исправленному плану. Статус: GET /runs/{id}.
         */
        post: operations["rebuild_api_v1_runs__run_id__rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Streets
         * @description Улицы пилотного проекта, готовые к прогону.
         *
         *     Пустой список - обычное дело: каталог собирается из датасета, а датасет монтируется
         *     не везде. Прогон по улице запускается полем `street` в POST /runs.
         */
        get: operations["streets_api_v1_streets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactOut */
        ArtifactOut: {
            /** Name */
            name: string;
            /**
             * Size Bytes
             * @description Размер файла; null, если его нет
             */
            size_bytes?: number | null;
            /** Url */
            url: string;
        };
        /** Body_create_photo_api_v1_runs__run_id__photos_post */
        Body_create_photo_api_v1_runs__run_id__photos_post: {
            /**
             * Hour
             * @default 11
             */
            hour: number;
            /**
             * Image
             * @description Кадр 3D-вида, PNG, стороны кратны 32, до 2048 px
             */
            image: string;
            /**
             * Scenery
             * @description Разрешить модели дорисовать фон и деревья, которых нет в плане
             * @default false
             */
            scenery: boolean;
            /** @default summer */
            season: components["schemas"]["Season"];
            /**
             * Shrubs
             * @description Латинские названия кустарников в кадре через запятую
             * @default
             */
            shrubs: string;
            /**
             * Species
             * @description Латинские названия деревьев в кадре через запятую
             * @default
             */
            species: string;
            /** @default aerial */
            viewpoint: components["schemas"]["Viewpoint"];
        };
        /** Body_create_run_api_v1_runs_post */
        Body_create_run_api_v1_runs_post: {
            /**
             * Extra
             * @description Остальные чертежи комплекта (DXF или DWG): склеиваются с основным
             */
            extra?: string[] | null;
            /**
             * File
             * @description Чертёж DXF или DWG; или street, но не оба
             */
            file?: string | null;
            /**
             * Inventory
             * @description Перечётная ведомость .xls или .xlsx: существующие деревья в квотах
             */
            inventory?: string | null;
            /**
             * Layers
             * @description Слои ГИС: GeoJSON (.geojson, .json) или SHP в .zip (.shp, .shx, .dbf, .prj) - охранные зоны, здания и границы data.mos.ru, кадастр. Класс объектов - по config/geo_layers.yaml или атрибуту green_class; WGS 84 пересчитывается в систему чертежа
             */
            layers?: string[] | null;
            /**
             * Overrides
             * @description JSON-объект параметров поверх профиля
             */
            overrides?: string | null;
            /**
             * Profile
             * @description Профиль параметров из /meta
             */
            profile?: string | null;
            /**
             * Street
             * @description Улица пилотного проекта из /streets (slug); или file
             */
            street?: string | null;
        };
        /**
         * CheckIn
         * @description Точка в координатах чертежа. Вид задаёт состав правил: нормы зависят от породы.
         */
        CheckIn: {
            /** Species */
            species?: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** CheckOut */
        CheckOut: {
            /** Checks */
            checks?: components["schemas"]["RuleCheckOut"][];
            /** Needs Barrier */
            needs_barrier: boolean;
            /**
             * Note
             * @default
             */
            note: string;
            /** Plantable */
            plantable: boolean;
            /** Verdict */
            verdict: string;
        };
        /** ConverterOut */
        ConverterOut: {
            /** Available */
            available: boolean;
            /** Name */
            name: string;
        };
        /**
         * DraftOut
         * @description Current in-memory draft; artifacts remain the last successful export.
         */
        DraftOut: {
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
            /** Quality */
            quality: {
                [key: string]: unknown;
            };
            /** Stale */
            stale: boolean;
        };
        /** EditIn */
        EditIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "move" | "delete" | "add";
            /** Placement Id */
            placement_id?: string | null;
            /** Species */
            species?: string | null;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
        };
        /** EditsIn */
        EditsIn: {
            /** Edits */
            edits: components["schemas"]["EditIn"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** MetaOut */
        MetaOut: {
            /** Converters */
            converters: components["schemas"]["ConverterOut"][];
            /** Default Profile */
            default_profile: string;
            /** Profiles */
            profiles: string[];
            /** Result Layers */
            result_layers: string[];
            rules: components["schemas"]["RulesOut"];
            /** Species */
            species: components["schemas"]["SpeciesOut"][];
            /** Version */
            version: string;
        };
        /** PhotoListOut */
        PhotoListOut: {
            /** Available */
            available: boolean;
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
            /**
             * Reason
             * @description Почему фото делать нельзя, если нельзя
             */
            reason: string | null;
        };
        /**
         * PhotoOut
         * @description Фото участка по кадру 3D-вида: задание очереди и ссылки на картинки.
         */
        PhotoOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Height */
            height: number;
            /** Hour */
            hour: number;
            /** Id */
            id: string;
            /**
             * Photo Url
             * @description Увеличенное фото, когда оно готово
             */
            photo_url: string | null;
            /**
             * Raw Url
             * @description Выход модели размером кадра
             */
            raw_url: string | null;
            /**
             * Scenery
             * @description Модель дорисовала фон и деревья, которых нет в плане
             */
            scenery: boolean;
            /** Season */
            season: string;
            /** Seconds */
            seconds: number | null;
            /** Shrubs */
            shrubs: string[];
            /** Source Url */
            source_url: string;
            /** Species */
            species: string[];
            /** Started At */
            started_at: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed";
            /** Upscaled */
            upscaled: boolean;
            /**
             * Viewpoint
             * @enum {string}
             */
            viewpoint: "aerial" | "ground";
            /** Width */
            width: number;
        };
        /**
         * PlanSummaryOut
         * @description Состояние плана после правки.
         *
         *     stale означает, что файлы результата уже не соответствуют плану на экране: правки
         *     приняты, но DXF и объяснения пересобираются отдельной командой.
         */
        PlanSummaryOut: {
            /** Allowed */
            allowed: number;
            /** Needs Approval */
            needs_approval: number;
            /** Placements */
            placements: number;
            /** Rejections */
            rejections: number;
            /** Stale */
            stale: boolean;
        };
        /** Problem */
        Problem: {
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[] | null;
            /** Instance */
            instance?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * ProfileOut
         * @description Параметры профиля, которые показывает форма запуска.
         *
         *     Форма заполняется ими и отправляет в overrides только изменённое человеком: иначе выбор
         *     профиля терялся под значениями формы по умолчанию.
         */
        ProfileOut: {
            /** Curb Hedges */
            curb_hedges: boolean;
            /**
             * Lawns
             * @description Газоны на грунте, который посадки оставили свободным
             */
            lawns: boolean;
            /**
             * Modes
             * @description Приёмы размещения: alley, lawn, fill
             */
            modes: string[];
            /** Name */
            name: string;
            /**
             * Planting Type
             * @description tree или shrub
             */
            planting_type: string;
            /** Root Barriers */
            root_barriers: boolean;
            /**
             * Shrub Fill
             * @description Группы кустарника на свободном газоне
             */
            shrub_fill: boolean;
            /** Shrub Groups */
            shrub_groups: boolean;
            /** Shrub Rows */
            shrub_rows: boolean;
            /**
             * Spacing M
             * @description Шаг посадки, м
             */
            spacing_m: number;
            /** Understory */
            understory: boolean;
        };
        /**
         * ProgressOut
         * @description Ход прогона: есть только пока он идёт.
         *
         *     Доля и остаток - оценка по весам этапов и прошедшему времени; подоснова для карты
         *     (`basemap.geojson`) появляется в `artifacts` раньше остальных файлов.
         */
        ProgressOut: {
            /**
             * Elapsed S
             * @description Секунд с начала расчёта
             */
            elapsed_s: number;
            /**
             * Eta S
             * @description Оценка остатка в секундах
             */
            eta_s: number | null;
            /**
             * Fraction
             * @description Доля сделанного, 0..1
             */
            fraction: number;
            /**
             * Stage
             * @description Текущий этап или null до первого этапа
             */
            stage: string | null;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /**
             * Title
             * @description Название этапа для человека
             */
            title: string;
        };
        /** RuleCheckOut */
        RuleCheckOut: {
            /** Measured M */
            measured_m?: number | null;
            /** Object Class */
            object_class?: string | null;
            /** Outcome */
            outcome: string;
            /** Rule Id */
            rule_id: string;
            /** Threshold M */
            threshold_m?: number | null;
        };
        /** RulesOut */
        RulesOut: {
            /** Fingerprint */
            fingerprint: string;
            /** Total */
            total: number;
            /** Verified */
            verified: number;
        };
        /** RunListOut */
        RunListOut: {
            /** Items */
            items: components["schemas"]["RunOut"][];
        };
        /** RunOut */
        RunOut: {
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Overrides */
            overrides: {
                [key: string]: unknown;
            };
            /** Profile */
            profile: string;
            /** @description Ход расчёта; null, пока прогон в очереди или уже закончен */
            progress?: components["schemas"]["ProgressOut"] | null;
            /** Source Name */
            source_name: string;
            state: components["schemas"]["RunState"];
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RunState
         * @enum {string}
         */
        RunState: "queued" | "running" | "succeeded" | "failed";
        /** @enum {string} */
        Season: "spring" | "summer" | "autumn" | "winter";
        /** SpeciesOut */
        SpeciesOut: {
            /** Code */
            code: string;
            /** Crown Diameter M */
            crown_diameter_m: number;
            /** Name Lat */
            name_lat: string;
            /** Name Ru */
            name_ru: string;
        };
        /** StepOut */
        StepOut: {
            /** Id */
            id: string;
            /**
             * Ms
             * @description Длительность завершённого этапа
             */
            ms?: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "done" | "active" | "pending";
            /** Title */
            title: string;
        };
        /**
         * StreetOut
         * @description Улица пилотного проекта, подготовленная в каталоге на диске.
         */
        StreetOut: {
            /** Files */
            files: number;
            /** Number */
            number: number;
            /** Size Mb */
            size_mb: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** @enum {string} */
        Viewpoint: "aerial" | "ground";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    profile_api_v1_profiles__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_run_api_v1_runs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_demo_run_api_v1_runs_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_artifact_api_v1_runs__run_id__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    check_api_v1_runs__run_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Состояние прогона изменилось */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    draft_api_v1_runs__run_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Состояние прогона изменилось */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    edit_api_v1_runs__run_id__edits_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummaryOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Состояние прогона изменилось */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_photos_api_v1_runs__run_id__photos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoListOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Сервис недоступен */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_photo_api_v1_runs__run_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_photo_api_v1_runs__run_id__photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Сервис недоступен */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_photo_api_v1_runs__run_id__photos__photo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Сервис недоступен */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_photo_file_api_v1_runs__run_id__photos__photo_id___kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                photo_id: string;
                kind: "source" | "raw" | "photo";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Сервис недоступен */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    rebuild_api_v1_runs__run_id__rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummaryOut"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Состояние прогона изменилось */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Данные не приняты */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Внутренняя ошибка сервиса */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    streets_api_v1_streets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreetOut"][];
                };
            };
        };
    };
}
